# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    \n"
"    \n"
"    background-color: rgb(38, 56, 90);\n"
"    \n"
"    color: rgb(198, 203, 207);\n"
"    border-radius: 10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_fourier = QtWidgets.QLabel(self.frame)
        self.label_fourier.setGeometry(QtCore.QRect(-50, 0, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        self.label_fourier.setFont(font)
        self.label_fourier.setStyleSheet("color: rgb(39, 247, 195);")
        self.label_fourier.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fourier.setObjectName("label_fourier")
        self.label_laplace = QtWidgets.QLabel(self.frame)
        self.label_laplace.setGeometry(QtCore.QRect(90, 60, 371, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        self.label_laplace.setFont(font)
        self.label_laplace.setStyleSheet("color: rgb(39, 247, 195);")
        self.label_laplace.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_laplace.setObjectName("label_laplace")
        self.lineEdit_laplace = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_laplace.setGeometry(QtCore.QRect(30, 210, 711, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_laplace.setFont(font)
        self.lineEdit_laplace.setObjectName("lineEdit_laplace")
        self.label_EnterLaplace = QtWidgets.QLabel(self.frame)
        self.label_EnterLaplace.setGeometry(QtCore.QRect(30, 170, 621, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_EnterLaplace.setFont(font)
        self.label_EnterLaplace.setStyleSheet("")
        self.label_EnterLaplace.setObjectName("label_EnterLaplace")
        self.label_EnterFourier = QtWidgets.QLabel(self.frame)
        self.label_EnterFourier.setGeometry(QtCore.QRect(30, 320, 621, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_EnterFourier.setFont(font)
        self.label_EnterFourier.setStyleSheet("")
        self.label_EnterFourier.setObjectName("label_EnterFourier")
        self.lineEdit_fourier = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_fourier.setGeometry(QtCore.QRect(30, 360, 711, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_fourier.setFont(font)
        self.lineEdit_fourier.setObjectName("lineEdit_fourier")
        self.pushButton_laplace = QtWidgets.QPushButton(self.frame)
        self.pushButton_laplace.setGeometry(QtCore.QRect(30, 260, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButton_laplace.setFont(font)
        self.pushButton_laplace.setStyleSheet("color: rgb(39, 247, 195);\n"
"background-color: rgb(105, 121, 175);")
        self.pushButton_laplace.setObjectName("pushButton_laplace")
        self.pushButton_laplaceInverse = QtWidgets.QPushButton(self.frame)
        self.pushButton_laplaceInverse.setGeometry(QtCore.QRect(390, 260, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButton_laplaceInverse.setFont(font)
        self.pushButton_laplaceInverse.setStyleSheet("color: rgb(39, 247, 195);\n"
"background-color: rgb(105, 121, 175);")
        self.pushButton_laplaceInverse.setObjectName("pushButton_laplaceInverse")
        self.pushButton_fourier = QtWidgets.QPushButton(self.frame)
        self.pushButton_fourier.setGeometry(QtCore.QRect(30, 410, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButton_fourier.setFont(font)
        self.pushButton_fourier.setStyleSheet("color: rgb(39, 247, 195);\n"
"background-color: rgb(105, 121, 175);")
        self.pushButton_fourier.setObjectName("pushButton_fourier")
        self.pushButton_fourierInverse = QtWidgets.QPushButton(self.frame)
        self.pushButton_fourierInverse.setGeometry(QtCore.QRect(390, 410, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButton_fourierInverse.setFont(font)
        self.pushButton_fourierInverse.setStyleSheet("color: rgb(39, 247, 195);\n"
"background-color: rgb(105, 121, 175);")
        self.pushButton_fourierInverse.setObjectName("pushButton_fourierInverse")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 470, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(39, 247, 195);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(100, 470, 671, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.pushButton_quit = QtWidgets.QPushButton(self.frame)
        self.pushButton_quit.setGeometry(QtCore.QRect(652, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setStyleSheet("background-color: rgb(105, 121, 175);\n"
"color: rgb(39, 247, 195);")
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.label_laplace.raise_()
        self.label_fourier.raise_()
        self.lineEdit_laplace.raise_()
        self.label_EnterLaplace.raise_()
        self.label_EnterFourier.raise_()
        self.lineEdit_fourier.raise_()
        self.pushButton_laplace.raise_()
        self.pushButton_laplaceInverse.raise_()
        self.pushButton_fourier.raise_()
        self.pushButton_fourierInverse.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton_quit.raise_()
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_fourier.setText(_translate("MainWindow", "Four<strong>ier"))
        self.label_laplace.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Lap</span>lace <span style=\" font-size:10pt;\">ver. 1.1</span></p></body></html>"))
        self.lineEdit_laplace.setText(_translate("MainWindow", "example: t^n (Laplace), 1/(p^2+3*p+2) (inverse Laplace)"))
        self.label_EnterLaplace.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Enter </span>a function for <span style=\" font-weight:600;\">Lap</span>lace transform or its inverse</p></body></html>"))
        self.label_EnterFourier.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Enter </span>a function for <span style=\" font-weight:600;\">Lap</span>lace transform or its inverse</p></body></html>"))
        self.lineEdit_fourier.setText(_translate("MainWindow", "example: exp(-x^2) (Fourier),  sqrt(pi)*exp(-(pi*k)^2) (inverse Fourier)"))
        self.pushButton_laplace.setText(_translate("MainWindow", "Laplace"))
        self.pushButton_laplaceInverse.setText(_translate("MainWindow", "Inverse Laplace"))
        self.pushButton_fourier.setText(_translate("MainWindow", "Fourier"))
        self.pushButton_fourierInverse.setText(_translate("MainWindow", "Inverse Fourier"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Res</span>ult:</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>The result will appear in a seperate window...</p><p><br/></p></body></html>"))
        self.pushButton_quit.setText(_translate("MainWindow", "QUIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

